# This config file is generatev by running `geth dumpconfig > <filename>`

[Eth]
NetworkId = 17
SyncMode = "full"
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightOnlyAnnounce = false
DatabaseCache = 2048
TrieCleanCache = 1024
TrieDirtyCache = 1024
TrieTimeout = 3600000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 8000000
GasCeil = 8000000
GasPrice = 1000000000
Recommit = 3000000000
Noverify = false

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
DatasetDir = "/root/.ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
PowMode = 0

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01
RestrictConnectionBetweenLightClients = true

[Node]
# This is the path to the datadir *in the container*
DataDir = "/root/.ethereum"
InsecureUnlockAllowed = true
HTTPHost = "172.16.1.100"
HTTPPort = 8545
HTTPModules = ["net", "web3", "eth", "shh"]
GraphQLPort = 8547
# Chainlink relies on geth for ethereum data, so expose its websocket service
WSHost = "172.16.1.100" # Fill this in with the IP address assigned to the node in docker-compose.yaml
WSPort = 8546
WSOrigins = ["*"]
WSModules = ["net", "web3", "eth", "shh"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30303"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Dashboard]
Host = "172.16.1.100"
Port = 8080
Refresh = 5000000000
